# Generated by Django 2.2.14 on 2020-11-19 17:05

import Forum.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Forum Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sub Forum Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forum Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=Forum.models.upload_to, verbose_name='Icon')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment Count')),
                ('topic_count', models.IntegerField(default=0, verbose_name='Topic Count')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.SubForum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
