# Generated by Django 2.2.14 on 2020-11-19 17:05

import Topic.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Konu başlığı giriniz.', max_length=50, validators=[Topic.models.min_length], verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(validators=[Topic.models.min_length], verbose_name='İçerik')),
                ('fixed', models.BooleanField(blank=True, default='False', editable=False, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=122, unique=True, verbose_name='Slug Alanı')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('craeted_comment_date', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.SubForum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İçerik Sahibi Sahibi')),
            ],
            options={
                'ordering': ['-craeted_comment_date'],
                'verbose_name_plural': 'Topics',
                'verbose_name': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(validators=[Topic.models.min_length], verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topic.Topic')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
